"""more updates

Revision ID: 30fc3e68da5a
Revises: 3243b6cd1a62
Create Date: 2024-12-28 22:56:51.018730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30fc3e68da5a'
down_revision = '3243b6cd1a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_frequency', sa.Integer(), nullable=True))
        batch_op.alter_column('weight_goal',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.alter_column('weight_goal',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('weekly_frequency')

    # ### end Alembic commands ###
