"""Change enum in user settings

Revision ID: d891b60d31b3
Revises: 601dbc190058
Create Date: 2024-12-28 10:03:28.565018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd891b60d31b3'
down_revision = '601dbc190058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.alter_column('theme',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('LIGHT', 'DARK', name='theme'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.alter_column('theme',
               existing_type=sa.Enum('LIGHT', 'DARK', name='theme'),
               type_=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
