"""update caseing

Revision ID: df1c8d29a144
Revises: 6262eac1c62c
Create Date: 2024-12-28 22:06:01.063116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df1c8d29a144'
down_revision = '6262eac1c62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('account_status', sa.Enum('ACTIVE', 'DEACTIVATED', 'ONBOARDING', name='accountstatus'), nullable=False))
        batch_op.drop_column('passwordHash')
        batch_op.drop_column('firstName')
        batch_op.drop_column('accountStatus')
        batch_op.drop_column('lastName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastName', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('accountStatus', mysql.ENUM('ACTIVE', 'DEACTIVATED', 'ONBOARDING', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), server_default=sa.text("'ONBOARDING'"), nullable=False))
        batch_op.add_column(sa.Column('firstName', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('passwordHash', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('account_status')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
